// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN30qeljRYoiPqqH0kuJCG6GuQx1TzaTg',
    appId: '1:355912082670:web:1c048907b5f1d1e05e3fff',
    messagingSenderId: '355912082670',
    projectId: 'receitas-qqjv5i',
    authDomain: 'receitas-qqjv5i.firebaseapp.com',
    storageBucket: 'receitas-qqjv5i.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT2yNSmBlr4RsfZ1kFdjicuviWccyGEzQ',
    appId: '1:355912082670:android:1a17dd8a3feaba3a5e3fff',
    messagingSenderId: '355912082670',
    projectId: 'receitas-qqjv5i',
    storageBucket: 'receitas-qqjv5i.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARe8wYn4QmOnzua34t1P_YcrVMenjbYP0',
    appId: '1:355912082670:ios:8b4499016d6049cf5e3fff',
    messagingSenderId: '355912082670',
    projectId: 'receitas-qqjv5i',
    storageBucket: 'receitas-qqjv5i.appspot.com',
    iosBundleId: 'com.example.testeFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARe8wYn4QmOnzua34t1P_YcrVMenjbYP0',
    appId: '1:355912082670:ios:29effdebdcd175ab5e3fff',
    messagingSenderId: '355912082670',
    projectId: 'receitas-qqjv5i',
    storageBucket: 'receitas-qqjv5i.appspot.com',
    iosBundleId: 'com.example.testeFirebase.RunnerTests',
  );
}
